#!/bin/python
import sys
import io

#Grabs relevant data from files generated by looptycho2.sh
#Call with "python grabdata.py <num> <precision>"
#where num and precision are the number and precision 
# in "tycho2_<precision>_<arch>_<num>.txt"

#Grab command line arguments
num = str(sys.argv[1])
prec = str(sys.argv[2])
arch='H'
#Make the input arguments a bit flexible
if (prec == 'single' or prec == 's'):
   prec = 'SINGLE'

if (prec == 'double' or prec == 'd'):
   prec = 'DOUBLE'

input_filename = 'tycho2_' + prec + '_' + arch + '_' + num + '.txt'

f = open(input_filename, 'r')#Open the file for reading

#Find maximum number of iterations
#Assume it is same for all runs
max_iter = 0
for line in f:
    if line[:13] == '   iteration:':
       current_iter = int(line.strip().split()[1])
       if current_iter > max_iter:
          max_iter = current_iter
f.close()

output_filename = 'tycho2_' + prec + '_' + arch + '_' + num + '_summary.txt'
out = open(output_filename, 'w')#Make an output file for writing
out.write('TotalIter, LastIterErr, TotSourceIterTime, TotTime, L2RelErr' + '\n')
f = open(input_filename, 'r')#Open the file for reading
for line in f:
    if line[:14 + len(str(max_iter))] == '   iteration: ' + str(max_iter):
       out.write(str(max_iter+1) + ", ")
       out.write(line[24 + len(str(max_iter)):36 + len(str(max_iter))] + ', ')
    if line[:28] == 'Total source iteration time:':
       out.write(line[29:-1] + ', ')
    if line[:11] == 'Total time:':
       out.write(line[12:-1] + ', ')
    if line[:18] == 'L2 Relative Error:':
       out.write(line[19:-1] + '\n')

out.close()
f.close()

